export const IMPRESSIONIST_STORY_SCHEMA = {
  title: 'Impressionist Story',
  subtitle: 'Painterly colour families for expressive mood direction.',
  kicker: 'Tier 1 - Identity',
  wrapperClassName: 'wireframe-template--impressionist',
  orbClassName: 'wireframe-template__orb--impressionist',
  tags: ['Expressive', 'Painterly', 'Soft-edged', 'Dreamlike'],
  tagIntents: {
    Expressive: 'Pushes colour relationships to carry feeling first, information second.',
    Painterly: 'Keeps gradients hand-blended and textured so transitions feel artistic, not mechanical.',
    'Soft-edged': 'Avoids harsh boundaries so hierarchy stays calm while remaining readable.',
    Dreamlike: 'Maintains atmospheric ambiguity that supports reflective storytelling flows.',
  },
  identityPoints: [
    'Brush-stroke gradient orb with subtle canvas grain',
    '24px padding rhythm and calm hierarchy',
    'Expressive mood direction aligned to template descriptor',
  ],
  coreSwatches: [
    ['#c6b5df', 'Lavender Mist'],
    ['#e6c2cb', 'Blush Petal'],
    ['#eacb8b', 'Soft Gold'],
    ['#adc2da', 'Haze Blue'],
    ['#d6cec1', 'Warm Neutral Canvas'],
    ['#5f4f69', 'Deep Mauve Shadow'],
  ],
  accentSwatches: [
    ['#f0b7c3', 'Highlight Bloom'],
    ['#5a5266', "Painter's Depth"],
  ],
  gradientClassName: 'wireframe-template__gradient--impressionist',
  lightMapClassName: 'wireframe-template__light-map--impressionist',
  lightMapLabel: 'Light map: Soft Diffused Glow (120x120 reference).',
  atmosphereClassName: 'wireframe-template__scene--impressionist',
  textureClassName: 'wireframe-template__texture--impressionist',
  miniSceneClassName: 'wireframe-template__mini-scene--impressionist',
  atmospherePoints: [
    'Soft brush strokes and blended colour transitions',
    'Impressionist haze with painted-feeling light',
    'Canvas texture, watercolour grain, and soft linen neutrals',
  ],
  emotionalNotes: ['Expressive', 'Soft', 'Blended', 'Dreamlike'],
  seasonalNotes: [
    'Works beautifully for Spring and Autumn palettes',
    'Ideal for mood-driven storytelling',
    'Pairs well with soft serif typography',
  ],
  useCases: [
    'Creative landing pages',
    'Storytelling sequences',
    'Mood-driven editorial layouts',
    'Artistic onboarding flows',
  ],
  whyLayoutWorks: [
    'It respects the expressive, painterly nature of the category.',
    'It still follows the calm, structured hierarchy of your Moods Board.',
    'It introduces texture and softness without breaking the grid.',
    'It feels like a natural extension of the Reflections Family aesthetic.',
    "It aligns with the new feature's description on your page.",
  ],
};

export const RAINWASHED_WEATHER_SCHEMA = {
  title: 'Rainwashed Weather',
  subtitle: 'Softened tones shaped by rainfall, mist, and reflective surfaces.',
  kicker: 'Tier 1 - Identity',
  wrapperClassName: 'wireframe-template--rainwashed',
  orbClassName: 'wireframe-template__orb--rainwashed',
  tags: ['Calm', 'Washed', 'Reflective', 'Softened edges'],
  tagIntents: {
    Calm: 'Prioritizes low-contrast pacing so UI feels quiet and steady.',
    Washed: 'Softens saturation to mimic rain-muted surfaces and diffused light.',
    Reflective: 'Introduces subtle depth cues that suggest puddles and mirrored texture.',
    'Softened edges': 'Rounds visual boundaries to prevent sharp breaks in the emotional tone.',
  },
  identityPoints: [
    'Soft weather tone language',
    'Mist-to-blue orb accent with subdued opacity',
    '24px internal spacing rhythm with calm hierarchy',
  ],
  coreSwatches: [
    ['#c4c8cd', 'Mist Grey'],
    ['#8f9398', 'Wet Stone'],
    ['#9fb4c7', 'Soft Blue'],
    ['#edf1f3', 'Cloud White'],
    ['#727880', 'Storm Neutral'],
    ['#3f4650', 'Deep Rain Shadow'],
  ],
  accentSwatches: [
    ['#bed1df', 'Rain Glow'],
    ['#4f5d6b', 'Puddle Depth'],
  ],
  gradientClassName: 'wireframe-template__gradient--rainwashed',
  lightMapClassName: 'wireframe-template__light-map--rainwashed',
  lightMapLabel: 'Light map: Overcast Diffuse (120x120 reference).',
  atmosphereClassName: 'wireframe-template__scene--rainwashed',
  textureClassName: 'wireframe-template__texture--rainwashed',
  miniSceneClassName: 'wireframe-template__mini-scene--rainwashed',
  atmospherePoints: [
    'Wet pavement or blurred reflections',
    'Misty horizon with cool, even light',
    'Smooth stone, cotton grey, and matte paper grain',
  ],
  emotionalNotes: ['Calm', 'Reflective', 'Soft', 'Quiet'],
  seasonalNotes: [
    'Works well for rainy-day UI',
    'Ideal for wellness, calm apps, and editorial',
    'Pairs beautifully with neutral typography',
  ],
  useCases: [
    'Journaling interfaces',
    'Weather-aware UI',
    'Soft onboarding flows',
    'Reflective storytelling',
  ],
  whyLayoutWorks: [
    'It keeps the same architecture as Golden Evening for visual consistency.',
    'It introduces atmospheric softness without collapsing the hierarchy.',
    'It keeps emotional clarity while staying functional for implementation.',
    'It extends the Reflections Family tone with a calmer weather expression.',
  ],
};

export const CINEMATIC_FRAME_JEWEL_SCHEMA = {
  title: 'Cinematic Frame - Jewel-Tone Edition',
  subtitle: 'A richer, expressive cinematic palette with controlled light and atmospheric depth.',
  kicker: 'Tier 1 - Identity',
  wrapperClassName: 'wireframe-template--cinematic-jewel',
  orbClassName: 'wireframe-template__orb--cinematic-jewel',
  tags: ['Dramatic', 'High-contrast', 'Controlled light', 'Filmic'],
  tagIntents: {
    Dramatic: 'Uses stronger contrast separation so key visual moments read with confidence.',
    'High-contrast': 'Balances deep chromatic shadows against selective highlights for cinematic tension.',
    'Controlled light': 'Keeps light direction intentional so colour depth remains readable and calm.',
    Filmic: 'Frames composition like a still, with purposeful colour grading and atmospheric falloff.',
  },
  identityPoints: [
    'High-contrast orb with jewel-tone chroma and soft spotlight bloom',
    'High contrast, but not monochrome',
    'Structured rhythm with calm spacing and clear hierarchy',
    'Cinematic layout language tuned for richer colour storytelling',
  ],
  orbOptions: [
    {
      label: 'Cinematic (Charcoal)',
      blends: [
        { label: 'Noir Glow', colors: ['#e2d9c7', '#3b455f', '#1f2538', '#0b0f18'] },
        { label: 'Slate Spotlight', colors: ['#f0e2c2', '#49556f', '#242c44', '#111523'] },
        { label: 'Blue Steel Shadow', colors: ['#d8d2c6', '#4d6284', '#27324a', '#0d111c'] },
      ],
    },
    {
      label: 'Cinematic (Jewel-Tone)',
      blends: [
        { label: 'Sapphire Amethyst Gold', colors: ['#1f3a8a', '#5b2d82', '#d4af37', '#7b1e3a'] },
        { label: 'Garnet Teal Bloom', colors: ['#7b1e3a', '#0ea5a6', '#f2d3c3', '#5b2d82'] },
        { label: 'Velvet Gold Night', colors: ['#2c2f86', '#9f1239', '#d4af37', '#311749'] },
      ],
    },
  ],
  coreSwatches: [
    ['#1f3a8a', 'Deep Sapphire'],
    ['#7b1e3a', 'Garnet Red'],
    ['#5b2d82', 'Amethyst Violet'],
    ['#0f5132', 'Emerald Shadow'],
    ['#d4af37', 'Soft Gold Highlight'],
    ['#f2d3c3', 'Rose Quartz Light'],
  ],
  accentSwatches: [
    ['#0ea5a6', 'Electric Teal'],
    ['#9f1239', 'Ruby Glow'],
  ],
  gradientClassName: 'wireframe-template__gradient--cinematic-jewel',
  lightMapClassName: 'wireframe-template__light-map--cinematic-jewel',
  lightMapLabel: 'Light map: Coloured Key Light with jewel reflections (120x120 reference).',
  atmosphereClassName: 'wireframe-template__scene--cinematic-jewel',
  textureClassName: 'wireframe-template__texture--cinematic-jewel',
  miniSceneClassName: 'wireframe-template__mini-scene--cinematic-jewel',
  atmospherePoints: [
    'Sapphire blue shadows',
    'Gold highlights',
    'Deep red or violet accents',
    'Soft bloom',
    'Neon reflections',
    'Warm gold light on cool backgrounds',
    'Jewel-tone interiors',
    'High contrast without turning monochrome',
  ],
  texturePoints: [
    'Velvet in deep blue, red, or violet',
    'Brushed gold',
    'Satin or silk',
    'Soft grain film texture',
  ],
  miniScenePoints: [
    'Sapphire rectangle',
    'Gold highlight line',
    'Amethyst circle',
  ],
  emotionalNotes: ['Dramatic', 'Luminous', 'Filmic', 'Colour-driven'],
  seasonalNotes: [
    'Best for evening and night storytelling moments',
    'Works with selective highlights and deep chromatic shadows',
    'Pairs well with controlled serif or high-contrast sans typography',
  ],
  useCases: [
    'Hero sections with cinematic pacing',
    'Editorial sequences with colour-graded depth',
    'Mood-driven landing pages',
    'Story transitions with rich atmospheric cues',
  ],
  whyLayoutWorks: [
    'It keeps the same calm structure while increasing colour richness.',
    'It replaces flat greys with jewel tones without losing readability.',
    'It ties atmosphere image direction directly to cinematic lighting cues.',
    'It extends your existing template system without introducing one-off layout rules.',
  ],
};
